spring:
  application:
    name: eureka-server
server:
  port: ${PORT:8761}
  ip-address: ${ip-address:18.208.207.210}

#Configuracion para que no se autoregistre como cliente.
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
