# Application Config
spring:
 application:
  name: eureka-server
server:
  port: ${PORT:8761}
  ip-address: ${ip-address:0.0.0.0}

#Configuracion para que no se autoregistre como cliente.
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false